# Generated by Django 5.2.1 on 2025-05-23 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_test2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test2',
            name='question',
        ),
        migrations.DeleteModel(
            name='test1',
        ),
        migrations.DeleteModel(
            name='test2',
        ),
    ]
